import intf_libs = libsqlite3%lib{sqlite3}

lib{sqlite_orm}: hxx{**}
lib{sqlite_orm}: $intf_libs

out_inc = [dir_path] $out_root/include/
src_inc = [dir_path] $src_root/include/

lib{sqlite_orm}:
{
  cxx.export.poptions = "-I$out_inc" "-I$src_inc"
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
  lib{sqlite_orm}: bin.lib.version = "-$version.project_id"
else
  lib{sqlite_orm}: bin.lib.version = "-$version.major.$version.minor"

hxx{*}:
{
  install.subdirs = true
}
